### ISSUE TITLE
`prdoc generate` doesn't work

### ISSUE THREAD

**Issue by liamaharon** [paritytech/prdoc#20]
Running in `polkadot-sdk`:

```bash
$ prdoc --version
prdoc v0.0.7
$ prdoc generate 100
IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })%
```

It doesn't seem to matter which number I put, I always get this error.

My shell is `zsh` on MacOS.

**Comment by chevdor** [comment]
That's because there is no config yet in the repo. You can see more with `RUST_LOG=debug prdoc...`

Workaround until https://github.com/paritytech/polkadot-sdk/pull/1946 is merged is:
- create a folder outside of the repo
- put in there (you can take those from the PR above):
   - config
   - template
   - schema

Then set an ENV to tell `prdoc` to use that folder for the time being:
```
PRDOC_CONFIG=/your/temp/folder/config.toml
```

Alternatively, you can use:
```
prdoc generate --config /your/temp/folder/config.toml ...
```

**Comment by liamaharon** [comment]
Ah makes sense, thanks.

Maybe the error can be improved.
