### ISSUE TITLE
Release to crates-io

### ISSUE THREAD

**Issue by ggwpez** [paritytech/prdoc#36]
0.0.8 has not made it here yet: https://crates.io/crates/prdoc

**Comment by mutantcornholio** [comment]
Turns out that @chevdor still owns `prdoc` and `prdoclib` at crates.io when I asked about it in DM, he refused to add parity account to owners: 

> I did consider the options for the prdoc publishing on crates.io and I think it would be best for parity to publish to a parity crate such as some `parity-prdoc` for instance.  
I am not "in line" with some of the recent changes to the source and I want to keep `prdoc` a generic tool as it was originally designed.  
That will also give you/parity more freedom about regarding the next version and its features

I guess, we'll have to publish it as `parity-prdoc` / `parity-prdoclib`

**Comment by mutantcornholio** [comment]
Do we actually need a separate crate for prdoclib? Why not provide both `bin` and `lib` from the same crate?

**Comment by ggwpez** [comment]
Yea, then we should possibly also rename the repo to `parity-prdoc` to reflect this.

**Comment by mutantcornholio** [comment]
https://crates.io/crates/parity-prdoc
